### ISSUE TITLE
Why would you show a notification and not output to CLI?

### ISSUE THREAD

**Issue by dpacmittal** [technowar/Imgur-CLI#4]
CLI is supposed to work in pure CLI environments. I don't see any output on the CLI when I try to upload an image. Instead it notifies me that it has copied the link to the clipboard (which didn't work, by the way). I understand, showing notifications is convenient when you're using the listen feature but one time uploads showing notifications make no sense.

**Comment by technowar** [comment]
I have updated the code, and will display upload url to terminal. Please update current version.
