### ISSUE TITLE
does not copy to clipboard and does not output to terminal either

### ISSUE THREAD

**Issue by ta3pks** [technowar/Imgur-CLI#5]
does not copy to clipboard and does not output to terminal either so if i use this with no gui this script will not be able to work or at leas i cannot get the url of uploaded file

**Comment by technowar** [comment]
That's weird as I am getting the output. Please see http://i.imgur.com/0TdQwIq.png

**Comment by technowar** [comment]
I have updated the code, and will display upload url to terminal. Please update current version.
